# Generated by Django 2.2.3 on 2019-08-30 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardDict',
            fields=[
                ('attribute_ch_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('attribute_code', models.CharField(max_length=500)),
                ('attribute_en_name', models.CharField(max_length=500)),
                ('attribute_ch_desc', models.TextField(blank=True, null=True)),
                ('attribute_val_dmn', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
